#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=':' read -r username _ userid groupid _ homedir shell
do
    read -r _ _ _ _ _ _ _ _ _ _ passcode _ < <(grep "^$username:" /etc/shadow)

    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: USER ID INFO"
done < /etc/passwd
